services:
  system:
    image: ghcr.io/kirill-ivanovvv/owwo-system:latest
    ports:
      - "2222:22"
    env_file:
      - ./.env
    volumes:
      - shared-uploads:/home/uploads

  site:
    image: ghcr.io/kirill-ivanovvv/owwo-site:latest
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - shared-uploads:/home/uploads
    networks:
      - site-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - site
    networks:
      - site-network

volumes:
  shared-uploads:

networks:
  site-network:
    driver: bridge
